try: 
    raise Exception("test")
except Exception as e:
    print(e)